global:
  nameOverride: ""
  fullnameOverride: ""
  timeout: 10m

vault:
  enabled: true
  image: "hashicorp/vault:1.21"
  devRootToken: "root"
  devListen: "0.0.0.0:8200"
  service:
    port: 8200

storage:
  data:
    enabled: true
    existingClaim: ""
    storageClassName: "standard"
    accessModes: ["ReadWriteOnce"]
    size: 100Mi
  keys:
    enabled: true
    existingClaim: ""
    storageClassName: "standard"
    accessModes: ["ReadWriteOnce"]
    size: 10Mi

seed:
  # replaces docker-compose ./dev mount. Put alice public key here.
  enabled: true
  alicePublicKey: "" # e.g. "ssh-ed25519 AAAAC3... alice@local"

jobs:
  datainit:
    enabled: true
    image: "debian:bookworm-slim"
  hostkeygen:
    enabled: true
    image: "debian:bookworm-slim"
  vaultinit:
    enabled: true
    image: "curlimages/curl:8.18.0"

sftpServer:
  enabled: true
  image:
    repository: "go_sftp-sftp-server"
    tag: "latest"
    pullPolicy: IfNotPresent

  replicaCount: 2

  service:
    type: ClusterIP
    port: 2022
  metrics:
    enabled: true
    port: 9090
    path: /metrics

  env:
    LISTEN_ADDR: "0.0.0.0:2022"
    DATA_ROOT: "/data"
    HOST_KEY_PATH: "/keys/ssh_host_ed25519_key"
    VAULT_USERS_PREFIX: "secret/sftp/users"
    DEFAULT_QUOTA_BYTES: "10485760"
    DEFAULT_QUOTA_FILES: "50"
    METRICS_ADDR: "0.0.0.0:9090"
    METRICS_PATH: "/metrics"
    METRICS_INCLUDE_USER: "false"

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65534
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]

  resources: {}

adminApi:
  enabled: true
  image:
    repository: "go_sftp-admin-api"
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  env:
    LISTEN_ADDR: "0.0.0.0:8080"
    VAULT_USERS_PREFIX: "secret/sftp/users"

webUi:
  enabled: true
  image:
    repository: "go_sftp-web-ui"
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  env: {}

serviceMonitor:
  enabled: false
  interval: 15s
  scrapeTimeout: 10s
  labels: {}
