{{- if .Values.adminApi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftp.fullname" . }}-admin-api
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-api
spec:
  replicas: {{ .Values.adminApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "sftp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: admin-api
  template:
    metadata:
      labels:
        {{- include "sftp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: admin-api
    spec:
      containers:
        - name: admin-api
          image: "{{ .Values.adminApi.image.repository }}:{{ .Values.adminApi.image.tag }}"
          imagePullPolicy: {{ .Values.adminApi.image.pullPolicy }}
          env:
            - name: LISTEN_ADDR
              value: {{ .Values.adminApi.env.LISTEN_ADDR | quote }}
            - name: VAULT_USERS_PREFIX
              value: {{ .Values.adminApi.env.VAULT_USERS_PREFIX | quote }}
            {{- if .Values.vault.enabled }}
            - name: VAULT_ADDR
              value: "http://{{ include "sftp.vaultSvc" . }}:{{ .Values.vault.service.port }}"
            - name: VAULT_TOKEN
              value: {{ .Values.vault.devRootToken | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}-admin-api
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-api
spec:
  type: {{ .Values.adminApi.service.type }}
  selector:
    {{- include "sftp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin-api
  ports:
    - name: http
      port: {{ .Values.adminApi.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}

